statesources:
- class: EnergyPriceDataSource
  name: E_price
  normalise: abs_min_max
- class: WeatherDataSource
  name: weather
  normalise: abs_min_max
- class: InsideTemperature
  name: desired_temp_in
- class: DesiredUserEnergyNeed
  name: user_energy_need
- class: BuildingHeatLoss
  name: building_heat_loss
  K: 25
  mC: 200
- class: EVState
  name: ev_schedule
- class: OperatorEnergyControl
  name: operator_energy_control
  max_power_kW: 20.0
