statesources:
- class: DateSource
  name: date
- class: EnergyPriceDayDynDataSource
  name: E_price
- class: WeatherDataSource
  name: weather
- class: InsideTemperature
  name: desired_temp_in
- class: DesiredUserEnergyNeed
  name: user_energy_need
  ctxt_keys: [ctxt_hh_consumption_max]
- class: BuildingHeatLoss
  name: building_heat_loss
  ctxt_keys: [ctxt_building_K]
  K: 30
  mC: 150
- class: EVState
  name: ev_schedule
- class: OperatorEnergyControl
  name: operator_energy_control
  max_power_kW: 20.0
