statesources:
- class: EnergyPriceDynDataSource
  name: E_price
- class: WeatherDataSource
  name: weather
- class: InsideTemperature
  name: desired_temp_in
- class: DesiredUserEnergyNeed
  name: user_energy_need
- class: BuildingHeatLoss
  name: building_heat_loss
  emit_ctxt: true
  K: 20
  mC: 300
- class: EVState
  name: ev_schedule
- class: OperatorEnergyControl
  name: operator_energy_control
  max_power_kW: 20.0
