infras:
- class: HP
  name: HP
  max_power_kW: 1.0
  cop_heat: 3.0
  cop_cool: 2.5
- class: BatteryTremblay
  name: battery
  emit_ctxt: true
  cell_capacity_Ah: 4.3
  max_charge_A: 48.0
  start_soc: 0.3
  max_charge_rate: 1.5
  E0: 3.2
  K: 0.0063
  A: 0.468
  B: 2.47
  R_cell: 0.007
  n_series: 125
  n_parallel: 10
  charge_efficiency: 0.95
  discharge_efficiency: 0.95
  soc_min: 0.1
  soc_max: 0.95
- class: LinearEVCharger
  name: ev_charger
  max_power_kW: 22.0
  v2g_enabled: true
  max_charge_time_hrs: 24.0
  v2g_playroom: 0.1
- class: SolarPanel
  name: solar
  max_power_kW: 15.0
  pv_efficiency: 0.22
  panel_area_m2: 170
- class: HouseholdEnergyConsumers
  name: hh_consumers
  peak_consumption_kW: 8.0
